import Foundation

/// Rows recorded from the Rust originals — `decode_scheme_path`, `Path::extension`,
/// `image_content_type` and `http::Request::builder().uri` run verbatim in a
/// throwaway cargo program — so the Swift ports are held to Rust's answers, not to
/// a reading of them.
enum SchemeParityTables {
    enum Expected: Equatable {
        case ok(String)
        case err(String)
    }

    /// What `decode_scheme_path` answers for a URI as given. A `#` row is that raw
    /// function's answer only: Tauri never shows it a fragment (see `tauriURI`).
    static let decode: [(prefix: String, uri: String, expected: Expected)] = [
        ("tarmac-card://doc/", "tarmac-card://doc/%2Ftmp%2Fa.html?v=1", .ok("/tmp/a.html")),
        ("tarmac-card://doc/", "tarmac-card://doc/?v=1", .err("empty path")),
        ("tarmac-card://doc/", "tarmac-card://doc/", .err("empty path")),
        ("tarmac-card://doc/", "tarmac-card://doc/?", .err("empty path")),
        ("tarmac-card://doc/", "tarmac-card://doc/%FF?v=1", .err("invalid UTF-8 in path: invalid utf-8 sequence of 1 bytes from index 0")),
        ("tarmac-card://doc/", "tarmac-card://doc/a%zzb", .ok("a%zzb")),
        ("tarmac-card://doc/", "tarmac-card://doc/a%", .ok("a%")),
        ("tarmac-card://doc/", "tarmac-card://doc/a%4", .ok("a%4")),
        ("tarmac-card://doc/", "tarmac-card://doc/a%4?v=1", .ok("a%4")),
        ("tarmac-card://doc/", "tarmac-card://doc/%%41", .ok("%A")),
        ("tarmac-card://doc/", "tarmac-card://doc/%2f%2F", .ok("//")),
        ("tarmac-card://doc/", "tarmac-card://doc/a%23b%3Fc?v=1", .ok("a#b?c")),
        ("tarmac-card://doc/", "tarmac-card://doc/a#b?v=1", .ok("a#b")),
        ("tarmac-card://doc/", "tarmac-card://doc/a?b?c", .ok("a")),
        ("tarmac-card://doc/", "tarmac-card://doc/a b", .ok("a b")),
        ("tarmac-card://doc/", "tarmac-card://doc/\u{301}x.html", .ok("\u{301}x.html")),
        ("tarmac-card://doc/", "tarmac-card://doc/%CC%81x", .ok("\u{301}x")),
        ("tarmac-card://doc/", "tarmac-card://doc/%00a", .ok("\0a")),
        ("tarmac-card://doc/", "tarmac-card://doc/%E2%82", .err("invalid UTF-8 in path: incomplete utf-8 byte sequence from index 0")),
        ("tarmac-card://doc/", "tarmac-card://doc/%E2%82x", .err("invalid UTF-8 in path: invalid utf-8 sequence of 2 bytes from index 0")),
        ("tarmac-card://doc/", "tarmac-card://doc/%C0%80", .err("invalid UTF-8 in path: invalid utf-8 sequence of 1 bytes from index 0")),
        ("tarmac-card://doc/", "tarmac-card://doc/%ED%A0%80", .err("invalid UTF-8 in path: invalid utf-8 sequence of 1 bytes from index 0")),
        ("tarmac-card://doc/", "tarmac-card://doc/%F4%90%80%80", .err("invalid UTF-8 in path: invalid utf-8 sequence of 1 bytes from index 0")),
        ("tarmac-card://doc/", "tarmac-card://doc/ok%80", .err("invalid UTF-8 in path: invalid utf-8 sequence of 1 bytes from index 2")),
        ("tarmac-card://doc/", "tarmac-card://doc/ab%FFcd", .err("invalid UTF-8 in path: invalid utf-8 sequence of 1 bytes from index 2")),
        ("tarmac-card://doc/", "tarmac-card://doc/%F0%9F%98", .err("invalid UTF-8 in path: incomplete utf-8 byte sequence from index 0")),
        ("tarmac-card://doc/", "tarmac-card://doc/%F0%28%8C%28", .err("invalid UTF-8 in path: invalid utf-8 sequence of 1 bytes from index 0")),
        ("tarmac-card://doc/", "tarmac-card://doc/%F0%9F%98%80", .ok("\u{1f600}")),
        ("tarmac-card://doc/", "tarmac-card://doc/%EF%BB%BFa", .ok("\u{feff}a")),
        ("tarmac-card://doc/", "tarmac-card://doc/%E5%9C%96%E8%A1%A8.html", .ok("\u{5716}\u{8868}.html")),
        ("tarmac-card://doc/", "tarmac-card://doc/\u{5716}\u{8868}.html", .ok("\u{5716}\u{8868}.html")),
        ("tarmac-card://doc/", "tarmac-card://doc//x", .ok("/x")),
        ("tarmac-card://doc/", "tarmac-card://doc/%2F%2Fx", .ok("//x")),
        ("tarmac-card://doc/", "tarmac-card://doc/%2FUsers%2Fme%2Fmy-doc_v1.2%20(draft)!~*'.html?v=1700000000000", .ok("/Users/me/my-doc_v1.2 (draft)!~*'.html")),
        ("tarmac-card://doc/", "TARMAC-CARD://doc/x", .err("malformed tarmac-card URI: TARMAC-CARD://doc/x")),
        ("tarmac-card://doc/", "tarmac-card://DOC/x", .err("malformed tarmac-card URI: tarmac-card://DOC/x")),
        ("tarmac-card://doc/", "tarmac-card://doc", .err("malformed tarmac-card URI: tarmac-card://doc")),
        ("tarmac-card://doc/", "tarmac-card:/doc/x", .err("malformed tarmac-card URI: tarmac-card:/doc/x")),
        ("tarmac-card://doc/", "tarmac-card://img/x.png", .err("malformed tarmac-card URI: tarmac-card://img/x.png")),
        ("tarmac-card://doc/", "tarmac-card://other/foo.html", .err("malformed tarmac-card URI: tarmac-card://other/foo.html")),
        ("tarmac-card://doc/", "https://doc/foo.html", .err("malformed tarmac-card URI: https://doc/foo.html")),
        ("tarmac-card://doc/", "", .err("malformed tarmac-card URI: ")),
        ("tarmac-card://img/", "tarmac-card://img/%2Fd%2Fx.png?v=1", .ok("/d/x.png")),
        ("tarmac-card://img/", "tarmac-card://img/?v=1", .err("empty path")),
        ("tarmac-card://img/", "tarmac-card://img/%FF?v=1", .err("invalid UTF-8 in path: invalid utf-8 sequence of 1 bytes from index 0")),
        ("tarmac-card://img/", "tarmac-card://doc/x.png?v=1", .err("malformed tarmac-card URI: tarmac-card://doc/x.png?v=1")),
        ("tarmac-card://doc/", "tarmac-card://doc/%E0%80%AF", .err("invalid UTF-8 in path: invalid utf-8 sequence of 1 bytes from index 0")),
        ("tarmac-card://doc/", "tarmac-card://doc/%E0%9F%80", .err("invalid UTF-8 in path: invalid utf-8 sequence of 1 bytes from index 0")),
        ("tarmac-card://doc/", "tarmac-card://doc/%E0%A0%80", .ok("\u{800}")),
        ("tarmac-card://doc/", "tarmac-card://doc/%F0%80%80%AF", .err("invalid UTF-8 in path: invalid utf-8 sequence of 1 bytes from index 0")),
        ("tarmac-card://doc/", "tarmac-card://doc/%F0%8F%BF%BF", .err("invalid UTF-8 in path: invalid utf-8 sequence of 1 bytes from index 0")),
        ("tarmac-card://doc/", "tarmac-card://doc/%F0%90%80%80", .ok("\u{10000}")),
        ("tarmac-card://doc/", "tarmac-card://doc/%F4%8F%BF%BF", .ok("\u{10ffff}")),
        ("tarmac-card://doc/", "tarmac-card://doc/%F4%90%80%80", .err("invalid UTF-8 in path: invalid utf-8 sequence of 1 bytes from index 0")),
        ("tarmac-card://doc/", "tarmac-card://doc/%ED%9F%BF", .ok("\u{d7ff}")),
        ("tarmac-card://doc/", "tarmac-card://doc/%F0%9F%41%80", .err("invalid UTF-8 in path: invalid utf-8 sequence of 2 bytes from index 0")),
        ("tarmac-card://doc/", "tarmac-card://doc/%F0%9F%98%41", .err("invalid UTF-8 in path: invalid utf-8 sequence of 3 bytes from index 0")),
        ("tarmac-card://doc/", "tarmac-card://doc/%E2%82%41", .err("invalid UTF-8 in path: invalid utf-8 sequence of 2 bytes from index 0")),
        ("tarmac-card://doc/", "tarmac-card://doc/%F5%80%80%80", .err("invalid UTF-8 in path: invalid utf-8 sequence of 1 bytes from index 0")),
        ("tarmac-card://doc/", "tarmac-card://doc/%C2%41", .err("invalid UTF-8 in path: invalid utf-8 sequence of 1 bytes from index 0")),
        ("tarmac-card://doc/", "tarmac-card://doc/%C1%BF", .err("invalid UTF-8 in path: invalid utf-8 sequence of 1 bytes from index 0")),
        ("tarmac-card://doc/", "tarmac-card://doc/%80", .err("invalid UTF-8 in path: invalid utf-8 sequence of 1 bytes from index 0")),
        ("tarmac-card://doc/", "tarmac-card://doc/%F1%80%80", .err("invalid UTF-8 in path: incomplete utf-8 byte sequence from index 0")),
        ("tarmac-card://doc/", "tarmac-card://doc/x%F1%80%80%41", .err("invalid UTF-8 in path: invalid utf-8 sequence of 3 bytes from index 1")),
    ]

    static let extensions: [(path: String, ext: String?, contentType: String?)] = [
        ("/d/x.png", .some("png"), "image/png"),
        ("/d/x.PNG", .some("PNG"), "image/png"),
        ("/d/x.png/", .some("png"), "image/png"),
        ("/d/x.png//", .some("png"), "image/png"),
        ("/d/x.png/.", .some("png"), "image/png"),
        ("/d/x.png/./", .some("png"), "image/png"),
        ("/d/x.png/..", .none, nil),
        ("/d/..", .none, nil),
        ("/d/.", .none, nil),
        ("/", .none, nil),
        ("", .none, nil),
        (".", .none, nil),
        ("..", .none, nil),
        ("./x.png", .some("png"), "image/png"),
        ("./.", .none, nil),
        ("x.png", .some("png"), "image/png"),
        (".png", .none, nil),
        ("/d/.png", .none, nil),
        ("/d/..png", .some("png"), "image/png"),
        ("/d/a..png", .some("png"), "image/png"),
        ("/d/x.", .some(""), nil),
        ("/d/x..", .some(""), nil),
        ("/d/x.png.txt", .some("txt"), nil),
        ("/d/README", .none, nil),
        ("/d/.hidden.png", .some("png"), "image/png"),
        ("/d/x.\u{301}png", .some("\u{301}png"), nil),
        ("/d/x.png\u{301}", .some("png\u{301}"), nil),
        ("/a.txt/\u{301}.png", .some("png"), "image/png"),
        ("/d/x.KTX", .some("KTX"), "image/ktx"),
        ("/d/x.\u{212a}tx", .some("\u{212a}tx"), nil),
        ("/d/x.\u{17f}vg", .some("\u{17f}vg"), nil),
        ("/d/x.png\0", .some("png\0"), nil),
        ("/d/a.png/b", .none, nil),
        ("/d.png/b", .none, nil),
        ("//d//x.png", .some("png"), "image/png"),
        ("/d/./x.png", .some("png"), "image/png"),
        ("/d/../x.png", .some("png"), "image/png"),
        ("/d/x.png/../y", .none, nil),
        ("/d/x.png/../y.jpg", .some("jpg"), "image/jpeg"),
        ("x", .none, nil),
        ("a/.", .none, nil),
        ("./", .none, nil),
        ("/.png", .none, nil),
        ("/d/.png.", .some(""), nil),
        ("/d/x.png ", .some("png "), nil),
        ("/d/ x.png", .some("png"), "image/png"),
        ("/d/x .png", .some("png"), "image/png"),
        ("/d/x.jp\0g", .some("jp\0g"), nil),
        ("/d/x.jpeg/", .some("jpeg"), "image/jpeg"),
        ("/d/x.JpEg", .some("JpEg"), "image/jpeg"),
        ("/d/x.x-png", .some("x-png"), "image/png"),
        ("/d/x.jfif-tbnl", .some("jfif-tbnl"), "image/jpeg"),
        ("/d/a.b.c.svg", .some("svg"), "image/svg+xml"),
        ("...", .some(""), nil),
        ("/d/...png", .some("png"), "image/png"),
        ("/d/x.png/.//./", .some("png"), "image/png"),
        ("./x", .none, nil),
        ("./..", .none, nil),
        ("././x.png", .some("png"), "image/png"),
    ]

    /// The test's own copy of Appendix A (spec 2609.0014), lifted from
    /// `image_protocol.rs`'s `every_appendix_a_extension_maps_to_exactly_its_type`.
    static let appendixA: [(String, String)] = [
        ("apng", "image/apng"),
        ("art", "image/x-jg"),
        ("avci", "image/avci"),
        ("avcs", "image/avcs"),
        ("avif", "image/avif"),
        ("azv", "image/vnd.airzip.accelerator.azv"),
        ("b16", "image/vnd.pco.b16"),
        ("bm", "image/bmp"),
        ("bmp", "image/bmp"),
        ("btf", "image/prs.btif"),
        ("btif", "image/prs.btif"),
        ("djv", "image/vnd.djvu"),
        ("djvu", "image/vnd.djvu"),
        ("dpx", "image/dpx"),
        ("drle", "image/dicom-rle"),
        ("dwg", "image/vnd.dwg"),
        ("dxf", "image/vnd.dxf"),
        ("emf", "image/emf"),
        ("exr", "image/aces"),
        ("fbs", "image/vnd.fastbidsheet"),
        ("fif", "image/fif"),
        ("fits", "image/fits"),
        ("flo", "image/florian"),
        ("fpx", "image/vnd.fpx"),
        ("fst", "image/vnd.fst"),
        ("g3", "image/g3fax"),
        ("gif", "image/gif"),
        ("hdr", "image/vnd.radiance"),
        ("heic", "image/heic"),
        ("heics", "image/heic-sequence"),
        ("heif", "image/heif"),
        ("heifs", "image/heif-sequence"),
        ("hej2", "image/hej2k"),
        ("hif", "image/heif"),
        ("hsj2", "image/hsj2"),
        ("ico", "image/vnd.microsoft.icon"),
        ("ief", "image/ief"),
        ("iefs", "image/ief"),
        ("j2c", "image/j2c"),
        ("j2k", "image/j2c"),
        ("jfif", "image/jpeg"),
        ("jfif-tbnl", "image/jpeg"),
        ("jhc", "image/jphc"),
        ("jls", "image/jls"),
        ("jp2", "image/jp2"),
        ("jpe", "image/jpeg"),
        ("jpeg", "image/jpeg"),
        ("jpf", "image/jpx"),
        ("jpg", "image/jpeg"),
        ("jpg2", "image/jp2"),
        ("jpgm", "image/jpm"),
        ("jph", "image/jph"),
        ("jpm", "image/jpm"),
        ("jps", "image/x-jps"),
        ("jpx", "image/jpx"),
        ("jut", "image/jutvision"),
        ("jxl", "image/jxl"),
        ("jxr", "image/jxr"),
        ("jxra", "image/jxrA"),
        ("jxrs", "image/jxrS"),
        ("jxs", "image/jxs"),
        ("jxsc", "image/jxsc"),
        ("jxsi", "image/jxsi"),
        ("jxss", "image/jxss"),
        ("ktx", "image/ktx"),
        ("ktx2", "image/ktx2"),
        ("mcf", "image/vasa"),
        ("mdi", "image/vnd.ms-modi"),
        ("mmr", "image/vnd.fujixerox.edmics-mmr"),
        ("nap", "image/naplps"),
        ("naplps", "image/naplps"),
        ("nif", "image/x-niff"),
        ("niff", "image/x-niff"),
        ("pbm", "image/x-portable-bitmap"),
        ("pct", "image/x-pict"),
        ("pcx", "image/vnd.zbrush.pcx"),
        ("pgb", "image/vnd.globalgraphics.pgb"),
        ("pgm", "image/x-portable-graymap"),
        ("pic", "image/vnd.radiance"),
        ("pict", "image/pict"),
        ("pm", "image/x-xpixmap"),
        ("png", "image/png"),
        ("pnm", "image/x-portable-anymap"),
        ("ppm", "image/x-portable-pixmap"),
        ("psd", "image/vnd.adobe.photoshop"),
        ("pti", "image/prs.pti"),
        ("qif", "image/x-quicktime"),
        ("qti", "image/x-quicktime"),
        ("qtif", "image/x-quicktime"),
        ("ras", "image/x-cmu-raster"),
        ("rast", "image/cmu-raster"),
        ("rf", "image/vnd.rn-realflash"),
        ("rgb", "image/x-rgb"),
        ("rgbe", "image/vnd.radiance"),
        ("rlc", "image/vnd.fujixerox.edmics-rlc"),
        ("rp", "image/vnd.rn-realpix"),
        ("s1g", "image/vnd.sealedmedia.softseal.gif"),
        ("s1j", "image/vnd.sealedmedia.softseal.jpg"),
        ("s1n", "image/vnd.sealed.png"),
        ("sgi", "image/vnd.sealedmedia.softseal.gif"),
        ("sgif", "image/vnd.sealedmedia.softseal.gif"),
        ("sjp", "image/vnd.sealedmedia.softseal.jpg"),
        ("sjpg", "image/vnd.sealedmedia.softseal.jpg"),
        ("spn", "image/vnd.sealed.png"),
        ("spng", "image/vnd.sealed.png"),
        ("sub", "image/vnd.dvb.subtitle"),
        ("svf", "image/vnd.dwg"),
        ("svg", "image/svg+xml"),
        ("t38", "image/t38"),
        ("tap", "image/vnd.tencent.tap"),
        ("tfx", "image/tiff-fx"),
        ("tif", "image/tiff"),
        ("tiff", "image/tiff"),
        ("turbot", "image/florian"),
        ("uvg", "image/vnd.dece.graphic"),
        ("uvi", "image/vnd.dece.graphic"),
        ("uvvg", "image/vnd.dece.graphic"),
        ("uvvi", "image/vnd.dece.graphic"),
        ("vtf", "image/vnd.valve.source.texture"),
        ("wbmp", "image/vnd.wap.wbmp"),
        ("webp", "image/webp"),
        ("wmf", "image/wmf"),
        ("x-png", "image/png"),
        ("xbm", "image/xbm"),
        ("xif", "image/vnd.xiff"),
        ("xpm", "image/xpm"),
        ("xwd", "image/x-xwd"),
        ("xyze", "image/vnd.radiance"),
    ]

    /// wry hands Tauri's handler `Request::builder().uri(absoluteString)`, and
    /// `http::Uri` drops everything from the first `#` — a `?` after it included.
    /// Each row is the URL a WKURLSchemeTask carries and the URI Rust's `respond`
    /// is then given.
    static let tauriURI: [(url: String, seen: String)] = [
        ("tarmac-card://doc/%2Ftmp%2Fa.html#frag", "tarmac-card://doc/%2Ftmp%2Fa.html"),
        ("tarmac-card://doc/%2Ftmp%2Fa.html?v=1#frag", "tarmac-card://doc/%2Ftmp%2Fa.html?v=1"),
        ("tarmac-card://doc/%2Ftmp%2Fa.html#frag?v=1", "tarmac-card://doc/%2Ftmp%2Fa.html"),
        ("tarmac-card://img/%2Ftmp%2Fa.png#frag", "tarmac-card://img/%2Ftmp%2Fa.png"),
        ("tarmac-card://img/%2Ftmp%2Fa.png?v=1#frag", "tarmac-card://img/%2Ftmp%2Fa.png?v=1"),
        ("tarmac-card://doc/a#b?v=1", "tarmac-card://doc/a"),
        ("tarmac-card://doc/a#b#c", "tarmac-card://doc/a"),
        ("tarmac-card://doc/a#", "tarmac-card://doc/a"),
        ("tarmac-card://doc/%2Ftmp%2Fa%23b.html#frag", "tarmac-card://doc/%2Ftmp%2Fa%23b.html"),
        ("tarmac-card://doc/%2Ftmp%2Fa%23b.html", "tarmac-card://doc/%2Ftmp%2Fa%23b.html"),
        ("tarmac-card://doc/?v=1#x", "tarmac-card://doc/?v=1"),
        ("tarmac-card://doc/#x", "tarmac-card://doc/"),
    ]
}
